###

GET http://localhost:3002


###
POST http://localhost:3002
Content-Type: application/json

{
    "sec_name": "Secction 1"
}


###

GET http://localhost:3002/6743f5548c5882b58f402363


###

POST http://localhost:3002/6743f5548c5882b58f402363
Content-Type: application/json

{
    "name": "pen",
    "mean" : "Bút",
    "api": "/pen/"
}
